# http://travis-ci.org/#!/jupyter/jupyter_core
language: python
dist: xenial

jobs:
  include:
    - name: "python nightly on xenial linux"
      python: "nightly"
    - name: "python 3.8 on xenial linux"
      python: "3.8"
    - name: "python 3.7 on xenial linux"
      python: "3.7"
    - name: "python 3.6 on xenial linux"
      python: "3.6"
    - name: "python 3.5 on xenial linux"
      python: "3.5"
    - name: "python 2.7 on xenial linux"
      python: "2.7"
    - name: "python 3.7 on macos"
      os: osx
      osx_image: xcode11.6
      language: shell
  allow_failures:
    - name: "python nightly on xenial linux"
      python: "nightly"

before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
install:
  - pip install -r dev-requirements.txt .
script:
  - py.test jupyter_core
