#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
"""Migrate Jupyter config from IPython < 4.0"""
from __future__ import annotations

from jupyter_core.migrate import main

if __name__ == "__main__":
    main()
